### ISSUE TITLE
Use asyncpg over psycopg2

### ISSUE THREAD

**Issue by TimMcGilly** [adampy/adambot#1]
I would recommend updating the bot to use asyncpg over psycogpg2 because discord.py is a asynchronous software so using a non-asynchronous db library with it could cause significant issues. 
Asyncpg is also extremely fast and according to them it is faster than psycogpg2. 
Asyncpg is also the recommended library by the discord.py devs for db actions.
https://github.com/MagicStack/asyncpg
I've used it in my own bots and it is fairly simple to set up. I have a few basic examples using it in https://github.com/TotallyCoded/Simple-Example-Discord.py-Bot and I expect migrating to it wouldn't be very difficult.

**Comment by adampy** [comment]
Hey, sorry for the year long delay! I am soon going to start changing over from psycopg2 to asyncpg so I will be looking at your example and the documentation closely next couple of days. Thank you 👍

**Comment by adampy** [comment]
Adam-Bot has been migrated from psycopg2 to asyncpg as requested. Thank you for the bringing asyncpg to my attention, Tim!
