### ISSUE TITLE
discord.py is back under development

### ISSUE THREAD

**Issue by raven0034** [adampy/adambot#40]
We need to assess whether or not it is feasible to move back to Discord.py, what needs to be changed (if anything), and when we should consider implementing features like slash commands (my current thoughts on this are to run slash commands alongside the classic commands, e.g. I suspect we will have great difficulty implementing some of the more "creative" features (like the custom command actions) using slash commands, and I also think it will be helpful to at least have a transition period.

**Comment by adampy** [comment]
Discord.py does have the advantage that it was the go-to for many a year for Discord bots written in Python, and I think that it'll once again be that in the future. I see that Rapptz has implemented slash commands in Discord.py. Am I right in thinking that slash commands are highly recommended but they are not _required_ for bots in under 75 servers?

**Comment by raven0034** [comment]
Yes, Discord does seem to be heavily pushing them but not requiring them for unverified bots, in our specific instance we don't _have_ to implement slash commands as of yet (and we don't need to meet the April 1st deadline since our instance is in less than 75 guilds), however I think they would be nice to play around with, show examples of and have available etc if we decide to expand.

I'm not 100% sure on this _but_ I believe that applications that have legitimate usages for the message intent (where the bot needs to be verified) can also continue using the classic commands system (e.g. we have logging and filtering which _requires_ message content access), although I will double check this at some point.

**Comment by adampy** [comment]
I don't think there is much functionality that depends purely on Pycord, and therefore it wouldn't be too much pain to get the bot moved back onto Discord.py, right?

Also I agree, slash commands are something we will need to implement to reduce the number of times we use message content, but as you've said I'm not sure how custom commands will work. Perhaps we will need to write a sort of small lexer to translate custom commands into actual commands.

**Comment by raven0034** [comment]
I'll have a dig through the commit history when I have a bit of time, I vaguely remember having to make a couple of commits to adapt things specifically for Pycord versus the dpy commit we were on before, but nothing too major. I'll also have a look at what has been changed since dpy was picked back up.

**Comment by raven0034** [comment]
Progress update: turned out there was quite a few more changes than I initially anticipated, a lot wrt https://gist.github.com/Rapptz/6706e1c8f23ac27c98cee4dd985c8120 , the new message content intent now being implemented and the command decorators breaking for some bizarre reason I haven't spotted yet.

https://github.com/adampy/adambot/commit/d895919944f76f0b20efb58d17069461db6a1d82
This commit should (hopefully) provide all the changes needed for the migration back.
